#!/usr/bin/env node
'use strict';

var SharedStore = require('../');
var httpResource = require('../lib/http');

function fetchData(headers) {
  return Promise.resolve({
    url: 'http://my-url',
    response: {
      headers: {
        'last-modified': new Date().toString(),
        'etag': 'some-etag'
      }
    },
    body: { incoming: headers, crashing: false }
  }).then(value => {
    return new Promise((resolve) => {
      // delay to ensure temp reads are faster
      setTimeout(resolve, 1000, value);
    });
  });
}

var options = {
  temp: process.argv[2],
  active: true,
  loader: function(baseConfig) {
    return httpResource({ fetch: fetchData });
  }
};

function unexpectedError(err) {
  process.nextTick(() => { throw err; });
}

new SharedStore(options).init({})
  .then(function(config) {
    if (config.crashing) {
      throw new Error('Expected crash')
    } else {
      console.log('ok');
      process.exit(0);
    }
  })
  .catch(unexpectedError);
